baseURL = 'https://mrquantum1915.github.io/'
languageCode = 'en-us'
title = 'Mr.Quantum_1915'
theme = 'custom-theme'

[params]
    description = "Quantum"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Projects'
    url = '/projects'
    weight = 20
  [[menus.main]]
    name = 'Blogs'
    url = '/blogs'
    weight = 30
  [[menus.main]]
    name = 'Contact'
    url = '/contact'
    weight = 40

[caches]
  [caches.images]
    dir = ':cacheDir/images'